name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Write configs and test
      env:
          APP_CONFIG: ${{secrets.APP_CONFIG}}
      run: |
        echo $APP_CONFIG | base64 -d > ./secrets/config.yaml
        cat ./secrets/config.yaml
        go test -v ./...
